# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apigw.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ .Values.apigw.name | quote }}
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  selector:
    name: {{ .Values.apigw.name | quote }}
  ports:
    - port: {{ .Values.apigw.mgmtPort }}
      name: mgmt
    - port: {{ .Values.apigw.apiPort }}
      name: api
