# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# Core pods are allowed to have view access to k8s APIs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-core
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
