# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if not .Values.db.external }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name | quote }}
  labels:
    name: {{ .Values.db.name | quote }}
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.db.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.db.name | quote }}
{{ include "openwhisk.label_boilerplate" . | indent 8 }}
    spec:
      restartPolicy: {{ .Values.db.restartPolicy }}

      {{- if .Values.affinity.enabled }}
      affinity:
{{ include "openwhisk.affinity.core" . | indent 8 }}
{{ include "openwhisk.affinity.selfAntiAffinity" ( .Values.db.name ) | indent 8 }}
      {{- end }}

      containers:
      - name: {{ .Values.db.name | quote }}
        imagePullPolicy: {{ .Values.db.imagePullPolicy | quote }}
        image: {{ .Values.db.image | quote }}
        ports:
        - name: couchdb
          containerPort: {{ .Values.db.port }}
        env:
        - name: "COUCHDB_USER"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_username
        - name: "COUCHDB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db.auth
              key: db_password
        - name: "NODENAME"
          value: "couchdb0"
        {{- if .Values.k8s.persistence.enabled }}
        volumeMounts:
          - name: database-storage
            mountPath: /opt/couchdb/data
        {{- end }}
      {{- if .Values.k8s.persistence.enabled }}
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: {{ .Values.db.persistence.pvcName | quote }}
      {{- end }}
{{ end }}
