# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if .Values.db.wipeAndInit }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-couchdb
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
data:
{{ (.Files.Glob "configMapFiles/initCouchDB/initdb.sh").AsConfig | indent 2 }}
{{ end }}
