# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{ if eq .Values.invoker.containerFactory.impl "kubernetes" }}
# When using KubernetesContainerFactory, invoker pods need extensive
# permissions to manage pods and deployments. The ability to create
# pods can enable privilege escalation attacks, so restrict it to a
# ServiceAccount that is only used for the invokers and only defined
# when using KubernetesContainerFactory.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-invoker
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
{{- end }}
