#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    name: {{ .Release.Name }}-nginx
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-nginx
{{ include "openwhisk.label_boilerplate" . | indent 8 }}
    spec:
      restartPolicy: {{ .Values.nginx.restartPolicy }}

      {{- if .Values.affinity.enabled }}
      affinity:
{{ include "openwhisk.affinity.edge" . | indent 8 }}
{{ include "openwhisk.affinity.selfAntiAffinity" ( printf "%s-nginx" .Release.Name ) | indent 8 }}
      {{- end }}

      {{- if .Values.toleration.enabled }}
      tolerations:
{{ include "openwhisk.toleration.edge" . | indent 8 }}
      {{- end }}

      volumes:
      {{- if or (eq .Values.whisk.ingress.type "NodePort") (eq .Values.whisk.ingress.type "LoadBalancer") }}
      {{- if .Values.nginx.certificate.external }}
      - name: nginx-certs
        configMap:
          name: {{ .Release.Name }}-gen-certs
      {{- else }}
      - name: nginx-certs
        secret:
          secretName: {{ .Release.Name }}-nginx
      {{- end }}
      {{- end }}
      - name: nginx-conf
        configMap:
          name: {{ .Release.Name }}-nginx
      - name: logs
        emptyDir: {}
{{ include "openwhisk.docker.imagePullSecrets" . | indent 6 }}
      initContainers:
      # Wait for a controller to be up (which implies kafka, zookeeper, couchdb are all up as well).
{{ include "openwhisk.readiness.waitForController" . | indent 6 }}
      containers:
      - name: nginx
        image: "{{- .Values.docker.registry.name -}}{{- .Values.nginx.imageName -}}:{{- .Values.nginx.imageTag -}}"
        imagePullPolicy: {{ .Values.nginx.imagePullPolicy | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.nginx.httpPort }}
        - name: https
          containerPort: {{ .Values.nginx.httpsPort }}
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
        {{- if or (eq .Values.whisk.ingress.type "NodePort") (eq .Values.whisk.ingress.type "LoadBalancer") }}
        - name: nginx-certs
          mountPath: "/etc/nginx/certs"
        {{- end }}
        - name: logs
          mountPath: "/logs"
