# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker.registry.auth
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
type: Opaque
data:
  docker_registry_username: {{ .Values.docker.registry.username | b64enc }}
  docker_registry_password: {{ .Values.docker.registry.password | b64enc }}
