# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db.auth
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
type: Opaque
data:
  db_username: {{ .Values.db.auth.username | b64enc }}
  db_password: {{ .Values.db.auth.password | b64enc }}
