# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Secret
metadata:
  name: whisk.auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  system: {{ .Values.whisk.auth.system | b64enc }}
  guest: {{ .Values.whisk.auth.guest | b64enc }}
