# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: batch/v1
kind: Job
metadata:
  name: install-package-kafka
  namespace: {{ .Release.Namespace | quote }}
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: install-package-kafka
    spec:
      restartPolicy: Never
      volumes:
      - name: task-dir
        configMap:
          name: install-package-kafka
      containers:
      - name: kafkapkginstaller
        image: openwhisk/script-runner
        volumeMounts:
        - name: task-dir
          mountPath: "/task/myTask.sh"
          subPath: "myTask.sh"
        env:
          - name: "AUTH"
            valueFrom:
              secretKeyRef:
                name: whisk.auth
                key: system
          # poorly named envvar; actually expects full apihost (host:port)
          - name: "APIHOST"
            valueFrom:
              configMapKeyRef:
                name: whisk.config
                key: whisk_api_host_nameAndPort
          # for the database used by kafka package
          - name: "DB_HOST"
            valueFrom:
              configMapKeyRef:
                name: db.config
                key: db_host
          - name: "DB_PORT"
            valueFrom:
              configMapKeyRef:
                name: db.config
                key: db_port
          - name: "DB_USERNAME"
            valueFrom:
              secretKeyRef:
                name: db.auth
                key: db_username
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db.auth
                key: db_password
          - name: "DB_PREFIX"
            value: "{{- .Values.kafkaprovider.dbPrefix -}}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-package-kafka
  namespace: {{ .Release.Namespace | quote }}
data:
{{ (.Files.Glob "configMapFiles/myTask.sh").AsConfig | indent 2 }}
