# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
description: An open source, distributed serverless platform that executes functions in response to events at any scale
name: openwhisk
version: 0.1.4
icon: https://raw.githubusercontent.com/apache/incubator-openwhisk/682eb5b62ee6ba8017ab54226c2ace3637f4f1ec/docs/images/whisk_icon_full-color_with_tm_64x64-300dpi.png
keywords:
  - Apache OpenWhisk
  - amd64
maintainers:
  - name: Apache OpenWhisk committers
    email: dev@openwhisk.apache.org
tillerVersion: ">=2.9.0"
kubeVersion: ">=v1.10.0-r0"
